# This workflow will build and test a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-frameworks/building-and-testing-java-with-maven

name: Run TestNG Tests with Maven

on:
  push:
    branches: [ main ] # Triggers the workflow on pushes to the main branch
  pull_request:
    branches: [ main ] # Triggers the workflow on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # Check out the repo

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Maven tests from Testngfile folder
        run: |
          cd Testngfile
          mvn verify
